"""阿里云号码认证服务（Dypnsapi）短信验证码发送客户端。

调用 SendSmsVerifyCode 让阿里云生成并发送验证码，并要求其在响应中
返回验证码明文（return_verify_code=True），由本服务自行存储与校验。
"""

from __future__ import annotations

import logging

from alibabacloud_dypnsapi20170525 import models as dypnsapi_models
from alibabacloud_dypnsapi20170525.client import Client as DypnsapiClient
from alibabacloud_tea_openapi import models as open_api_models
from alibabacloud_tea_util import models as util_models

from app.core.settings import Settings

logger = logging.getLogger(__name__)


class AliyunSmsError(Exception):
    """Raised when the Aliyun SMS provider rejects or fails a send request."""

    def __init__(self, provider_code: str, message: str) -> None:
        self.provider_code = provider_code
        super().__init__(message)


class AliyunSmsSender:
    """Sends verification codes through the Aliyun Dypnsapi SendSmsVerifyCode API."""

    def __init__(self, settings: Settings) -> None:
        self._settings = settings
        self._client = self._create_client(settings)

    @staticmethod
    def _create_client(settings: Settings) -> DypnsapiClient:
        config = open_api_models.Config(
            access_key_id=settings.aliyun_sms_access_key_id,
            access_key_secret=settings.aliyun_sms_access_key_secret,
        )
        config.endpoint = "dypnsapi.aliyuncs.com"
        return DypnsapiClient(config)

    def send_verification_code(self, phone: str) -> str:
        """Send a code via Aliyun and return the verify code generated by Aliyun."""
        request = dypnsapi_models.SendSmsVerifyCodeRequest(
            phone_number=phone,
            sign_name=self._settings.aliyun_sms_sign_name,
            template_code=self._settings.aliyun_sms_template_code,
            template_param=self._settings.aliyun_sms_template_param,
            country_code="86",
            code_type=1,  # digits-only code
            code_length=6,  # six-digit code; the login form expects 4-6 digits
            valid_time=5,  # minutes, matches the 300s TTL used by AuthService
            interval=60,  # Aliyun-enforced resend interval in seconds
            return_verify_code=True,
        )
        try:
            response = self._client.send_sms_verify_code_with_options(request, util_models.RuntimeOptions())
        except Exception as error:
            logger.error("Aliyun SMS send failed: phone=%s, error=%s", phone, error)
            raise AliyunSmsError("SMS_PROVIDER_UNAVAILABLE", "The SMS provider is temporarily unavailable.") from error
        body = response.body
        if body is None or body.code != "OK":
            provider_code = body.code if body is not None else "EMPTY_RESPONSE"
            provider_message = body.message if body is not None else "empty response"
            logger.error("Aliyun SMS send rejected: phone=%s, code=%s, message=%s", phone, provider_code, provider_message)
            raise AliyunSmsError(provider_code, f"SMS provider rejected the request: {provider_message}")
        verify_code = body.model.verify_code if body.model is not None else None
        if not verify_code:
            logger.error("Aliyun SMS send succeeded but no code returned: phone=%s, body=%s", phone, body.to_map())
            raise AliyunSmsError("SMS_PROVIDER_NO_CODE", "The SMS provider did not return a verification code.")
        logger.info("Aliyun SMS code sent: phone=%s", phone)
        return verify_code


def configured_aliyun_sms_sender(settings: Settings) -> AliyunSmsSender | None:
    """Build a sender when all required credentials are configured, else None.

    Test environments never build a real sender so tests never send paid SMS traffic.
    """
    if settings.app_env == "test":
        return None
    if not settings.aliyun_sms_access_key_id or not settings.aliyun_sms_access_key_secret:
        return None
    if not settings.aliyun_sms_sign_name or not settings.aliyun_sms_template_code:
        return None
    return AliyunSmsSender(settings)
